name: rl3d
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9
  - torchvision
  - cudatoolkit=11.1
  - pip
  - pip:
    - termcolor
    - gym==0.19.0
    - mujoco-py==2.1.2.14
    - pandas
    - wandb
    - moviepy
    - imageio
    - opencv-python
    - kornia
